### ISSUE TITLE
will the firmware binary will work on this ?

### ISSUE THREAD

**Issue by kolet** [acalatrava/openhaystack-firmware#11]
hi there ,
i am pretty new to all of this . ( i dont know how to compile , flash or have the requirement tools for it  but i will learn as i go , if i am missing or need to buy anything else please share thanks in advance .)

will this work on this ? (note there is 2/4 options.)
i dont know which one i should get 

2 with water proof case and 2 without i think they are the same except the water proof, but i still doesnt know the differences between the locate RSSI and the BEACON .

1, Beacon
2, RSSI
3, Beacon broadcast
4, Locate RSSI

which one do i get ? (and what are the differences)

https://www.aliexpress.com/item/32885909449.html?dp=cbk2pzevg8aqg8evooplmnr&cv=gooteis&aff_fcid=55daec68a7d14e90b1b548a2ed971e3f-1640358188177-03637-Ybe6y3B&aff_fsk=Ybe6y3B&aff_platform=aaf&sk=Ybe6y3B&aff_trace_key=55daec68a7d14e90b1b548a2ed971e3f-1640358188177-03637-Ybe6y3B&terminal_id=0847d94e233b4c4b95dc7362de6a809a

or this one 

https://www.aliexpress.com/item/1005002808176962.html?dp=cbk3pzevg5aqg8djwweljzb&cv=gooteis&aff_fcid=8d841974062c40529a54d7678b66bba9-1640358461294-09480-Ybe6y3B&aff_fsk=Ybe6y3B&aff_platform=aaf&sk=Ybe6y3B&aff_trace_key=8d841974062c40529a54d7678b66bba9-1640358461294-09480-Ybe6y3B&terminal_id=0847d94e233b4c4b95dc7362de6a809a

thanks alot !

**Comment by acalatrava** [comment]
Sorry for the (very long) delay. I guess you already picked one of them ;) Anyone should work since is the same chip, the only difference is that the second one is bigger and therefor battery should last a lot more.
