### ISSUE TITLE
flashed my device but cant deploy

### ISSUE THREAD

**Issue by jaekim24** [acalatrava/openhaystack-firmware#17]
Getting this error. Not sure what to do. 
<img width="995" alt="Screen Shot 2022-12-28 at 10 10 10 PM" src="https://user-images.githubusercontent.com/62858192/209898485-78c469fc-6ccb-45b7-a827-635283cfa7a8.png">

**Comment by jaekim24** [comment]
nevermind! You can right click and manually deploy it

**Comment by stmikul** [comment]
@jaekim24, can you explain more about what you mean by this? After dragging and dropping the firmware to my microbit v2, what are the next steps?

**Comment by stmikul** [comment]
@jaekim24, I dragged the .hex file to my Micro:bit v2, and it is displaying "OpenHaystack" on the LED panel but I'm not sure how to get this to deploy to the OpenHaystack macOS app to connect to the Find My network. Any help would be appreciated.
