### ISSUE TITLE
Nrf81522 128kb aliexpress

### ISSUE THREAD

**Issue by Giancky79** [acalatrava/openhaystack-firmware#18]
with the base command 

 NRF_MODEL=nrf51 BOARD=BOARD_ALIEXPRESS ADV_KEY_BASE64=YOUR_ADVERTISEMENT_KEY FLASH_KB=128 make patch

thanks for your work

**Comment by acalatrava** [comment]
`FLASH_KB` argument is not needed since is not used on the Makefile. Since the binary file fits on a 128KB flash it should work too on that chip. Did you test it?

**Comment by Giancky79** [comment]
Without, first time i had a problem with an error of out a space, but yes working very well.
Ii’m try to build openhaystack app but i don’t understand some command, from macos, working, i have traceroute , but problem with deploy for working day
