### ISSUE TITLE
Flash firmware with openocd works but there is no advertisement so far

### ISSUE THREAD

**Issue by mowtschan** [acalatrava/openhaystack-firmware#2]
I flashed nrf51 device with the firmware `apps/openhaystack-alternative/compiled/nrf51_firmware.bin` (without any modifications), I used openocd and stlink adapter. Flashing process worked without any issues but there is no advertisement so far, am I missing something?
```
Open On-Chip Debugger
> halt
target halted due to debug-request, current mode: Handler SVCall
xPSR: 0x6100000b pc: 0x000091f4 msp: 0x20003f48
> nrf51 mass_erase
nRF51822-QFAA(build code: H0) 256kB Flash, 16kB RAM
Mass erase completed.
A reset or power cycle is required if the flash was protected before.
> program /openhaystack-firmware/apps/openhaystack-alternative/compiled/nrf51_firmware.bin
target halted due to debug-request, current mode: Thread
xPSR: 0xc1000000 pc: 0xfffffffe msp: 0xfffffffc
** Programming Started **
Adding extra erase range, 0x0001cc70 .. 0x0001cfff
** Programming Finished **
> resume
> exit
```

**Comment by acalatrava** [comment]
Keep in mind that the advertisement is set to 5000 msec so you may miss some of the advertisements. For iPhone I saw that the eBeacon app (https://apps.apple.com/es/app/ebeacon-ble-scanner/id730279939) works better than others. Sometimes you may need to wait 20-30 seconds to see the first advertisement though.

**Comment by mowtschan** [comment]
I'm using the BlueSee app for macOS which is even better than the iPhone app

**Comment by acalatrava** [comment]
I installed BlueSee app and I don't see the device but I can see it on eBeacon on iPhone.... In fact I only see 2 devices on BlueSee while eBeacon shows me 6, including my TV... Not sure why

**Comment by mowtschan** [comment]
Did you install BlueSee app on mac or on iPhone?

**Comment by mowtschan** [comment]
anyway with BlueSee (on mac) I can exactly see which device is mine (I can see the public key of the device) but with all other tools I cannot see it

**Comment by acalatrava** [comment]
On Mac. Ok, I forgot to uncheck the filter to show only connectable devices... After some time the device appears:
![Captura de pantalla 2021-05-13 a las 12 10 40](https://user-images.githubusercontent.com/8502129/118111611-3e0eba00-b3e4-11eb-89de-4faf4ab4fb54.png)

**Comment by mowtschan** [comment]
do you have original openhaystack firmware or is it your alternative firmware? is it on nf51 device?

![image](https://user-images.githubusercontent.com/20609205/118112530-6c40c980-b3e5-11eb-8e60-7bcef00e3fef.png)

**Comment by acalatrava** [comment]
This is my alternative firmware just downloaded from releases and flash it on a nRF51 device. The only difference with you is that I flash it using JLink since I don't have STLink. But this is the same file you flash and on the same device....

**Comment by acalatrava** [comment]
It took some time to appear though, like 30-40 seconds

**Comment by mowtschan** [comment]
I can successfully build, flash (with stlink) and see advertising (with bluesee app) from example `nrf5x-base/apps/s130-beacon`:

![image](https://user-images.githubusercontent.com/20609205/118127106-8be1ed00-b3f9-11eb-8be1-5585c55b69fa.png)

but still no luck with your firmware :-/

**Comment by acalatrava** [comment]
Did you try to change the advertising interval?

**Comment by mowtschan** [comment]
`apps/openhaystack-alternative/main.c`

<img width="457" alt="image" src="https://user-images.githubusercontent.com/20609205/118128491-3f97ac80-b3fb-11eb-85aa-6a73a503a834.png">

**Comment by mowtschan** [comment]
it works! :-) (for my device nRF51822-QFAA) 
if I change `NRF_CLOCK_LFCLKSRC`:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/20609205/118139179-65c34980-b407-11eb-9692-dde75efa4233.png">

![image](https://user-images.githubusercontent.com/20609205/118140064-4e389080-b408-11eb-945b-b35b02f559c0.png)

**Comment by acalatrava** [comment]
Yeah! I thought about that but I couldn’t reply earlier. That’s because your board has no external crystal so you need to use the internal one. You can change this on the board_custom file instead or create a custom board file for your board.

**Comment by acalatrava** [comment]
Forced to not use an external crystal by default https://github.com/acalatrava/openhaystack-firmware/commit/1524dea6d9c57065447b7b9dec21872a9f07e234
