### ISSUE TITLE
Time Change Key

### ISSUE THREAD

**Issue by SergeKZ** [acalatrava/openhaystack-firmware#20]
Good evening. Where is the key change time set?

**Comment by acalatrava** [comment]
There's no key rotation implemented on this firmware. It will use the same key all the time. PR are welcome :)

**Comment by SergeKZ** [comment]
> There's no key rotation implemented on this firmware. It will use the same key all the time. PR are welcome :)

Can you add in the future?) to use 2 public keys?)

**Comment by SergeKZ** [comment]
Will more power be consumed if app_timer is added?
