### ISSUE TITLE
No Makefile

### ISSUE THREAD

**Issue by jaekim24** [acalatrava/openhaystack-firmware#3]
I'm trying to flash the nRF52 chip but I'm having a hard time. I'm new to all this, especially github, I tried running the "make build" command and I got this error message. 
<img width="418" alt="Screen Shot 2021-05-13 at 3 20 22 PM" src="https://user-images.githubusercontent.com/62858192/118175921-bda98280-b3fe-11eb-9479-1193e6fbff73.png">

**Comment by acalatrava** [comment]
You need to fetch the submodule. Go to the root directory and issue  
```
git submodule init
git submodule update
```

**Comment by jaekim24** [comment]
that fixed it !!

**Comment by jaekim24** [comment]
now when I enter "make build" I get this error at the bottom about "make: arm-none-eabi-gcc: No such file or directory" <img width="1006" alt="Screen Shot 2021-05-13 at 5 26 16 PM" src="https://user-images.githubusercontent.com/62858192/118189861-5399d900-b410-11eb-8d06-95c4248b2301.png">

**Comment by acalatrava** [comment]
You need to install this
https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-mac.pkg?revision=96309e24-064b-4aaf-81fc-9a4f2f15417e&la=en&hash=FB3A659BD38CEFCE2CF4EA78CBD95DA44ACE8AD9

**Comment by jaekim24** [comment]
I downloaded it but I still get the same error @acalatrava

**Comment by acalatrava** [comment]
I think you need to add it to your path. Try this

```
TOOLCHAIN_PATH=/Applications/ARM/bin make build

```

**Comment by jaekim24** [comment]
I still get the same error @acalatrava 
<img width="1006" alt="Screen Shot 2021-05-13 at 6 27 36 PM" src="https://user-images.githubusercontent.com/62858192/118195273-e5a5df80-b418-11eb-8382-9142babb1334.png">

**Comment by acalatrava** [comment]
Sorry I missed the latest /

```
TOOLCHAIN_PATH=/Applications/ARM/bin/ make build
```

**Comment by jaekim24** [comment]
I have this error now, I checked and I don't have a makefile. Do I have to make one?
<img width="1006" alt="Screen Shot 2021-05-14 at 12 08 01 AM" src="https://user-images.githubusercontent.com/62858192/118219923-73e58a00-b448-11eb-9a9d-32da91a8ab49.png">

**Comment by jaekim24** [comment]
new error after I typed TOOLCHAIN_PATH=/Applications/ARM/bin/ make build : 
<img width="1006" alt="Screen Shot 2021-05-14 at 1 18 48 AM" src="https://user-images.githubusercontent.com/62858192/118225057-56b5b900-b452-11eb-8b86-13787b70eed8.png">

**Comment by mowtschan** [comment]
`brew install binutils`

**Comment by jaekim24** [comment]
I still get the same error even after installing binutils

**Comment by jaekim24** [comment]
I still get the same error even after installing binutils

**Comment by mowtschan** [comment]
@jaekim24 can you post the output of the command `which objcopy` ?

**Comment by jaekim24** [comment]
"objcopy not found" @mowtschan

**Comment by acalatrava** [comment]
What about `which gobjcopy`

**Comment by jaekim24** [comment]
"gobjcopy not found"

**Comment by mowtschan** [comment]
@jaekim24 looks like it is missing in your `PATH`, can you run `export PATH="/usr/local/opt/binutils/bin:$PATH"` and try again?

p.s.: I assume that you have binutils installed on `/usr/local/opt/binutils/bin`

**Comment by jaekim24** [comment]
I think that worked, so with the new binary that's been created I use that to flash on to the compiled directory ?
<img width="1006" alt="Screen Shot 2021-05-14 at 6 10 42 PM" src="https://user-images.githubusercontent.com/62858192/118336445-b4441700-b4df-11eb-92c2-d82252af3d5d.png">

**Comment by jaekim24** [comment]
what's the next step I need to do to get the nrf52 chip to work w the find my network? @acalatrava

**Comment by acalatrava** [comment]
If you have a JLink you can just issue a `make flash`

**Comment by jaekim24** [comment]
what about the public advertisement key, Do I have to get that from the open haystack app?

**Comment by jaekim24** [comment]
im having this error where the "Target connection not established yet but required for command." 
<img width="1006" alt="Screen Shot 2021-05-16 at 8 44 39 PM" src="https://user-images.githubusercontent.com/62858192/118418709-8b5e8600-b687-11eb-84ec-e4b380eb9cf6.png">

**Comment by jaekim24** [comment]
and It also says cannot connect to target

<img width="1006" alt="Screen Shot 2021-05-16 at 8 46 48 PM" src="https://user-images.githubusercontent.com/62858192/118418772-d6789900-b687-11eb-8dbe-e2e009708372.png">

**Comment by jaekim24** [comment]
when I tried a new chip it did this:
michaelhunt@nicolaskerr openhaystack-alternative % TOOLCHAIN_PATH=/Applications/ARM/bin/ make flash
BUILD OPTIONS:
  SoftDevice  s132
  SDK         11
  nRF         nrf52832
  RAM         64 kB
  FLASH       512 kB
  Board       BOARD_SIMPLE
 
mkdir -p _build/
printf "r\n" > _build/flash.jlink
printf "loadfile _build/openhaystack-alternative_s132.hex \nr\ng\nexit\n" >> _build/flash.jlink
mkdir -p _build/
printf "r\nsavebin _build/downloaded_test.bin 0x1000 0x10\nexit\n" > _build/test-softdevice.jlink
mkdir -p _build/
SEGGER J-Link Commander V6.88a (Compiled Nov 18 2020 15:09:53)
DLL version V6.88a, compiled Nov 18 2020 15:09:35


J-Link Command File read successfully.
Processing script file...

J-Link connection not established yet but required for command.
Connecting to J-Link via USB...O.K.
Firmware: J-Link ARM-OB STM32 compiled Aug 22 2012 19:52:04
Hardware version: V7.00
S/N: 20090928
License(s): RDI,FlashDL,FlashBP,JFlash,GDBFull
VTref=3.300V
Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
Found SW-DP with ID 0x2BA01477
Unknown DP version. Assuming DPv0
Scanning AP map to find all available APs
AP[2]: Stopped AP scan as end of AP map has been reached
AP[0]: AHB-AP (IDR: 0x24770011)
AP[1]: JTAG-AP (IDR: 0x02880000)
Iterating through AP map to find AHB-AP to use
AP[0]: Core found
AP[0]: AHB-AP ROM base: 0xE00FF000
CPUID register: 0x410FC241. Implementer code: 0x41 (ARM)
Found Cortex-M4 r0p1, Little endian.
FPUnit: 6 code (BP) slots and 2 literal slots
CoreSight components:
ROMTbl[0] @ E00FF000
ROMTbl[0][0]: E000E000, CID: B105E00D, PID: 000BB00C SCS-M7
ROMTbl[0][1]: E0001000, CID: B105E00D, PID: 003BB002 DWT
ROMTbl[0][2]: E0002000, CID: B105E00D, PID: 002BB003 FPB
ROMTbl[0][3]: E0000000, CID: B105E00D, PID: 003BB001 ITM
ROMTbl[0][4]: E0040000, CID: B105900D, PID: 000BB9A1 TPIU
ROMTbl[0][5]: E0041000, CID: B105900D, PID: 000BB925 ETM
Cortex-M4 identified.
Reset delay: 0 ms
Reset type NORMAL: Resets core & peripherals via SYSRESETREQ & VECTRESET bit.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.

Opening binary file for writing... [_build/downloaded_test.bin]
Reading 16 bytes from addr 0x00001000 into file...O.K.


Script processing completed.

16+0 records in
16+0 records out
16 bytes transferred in 0.000131 secs (122016 bytes/sec)
Files _build/downloaded_test.bin and _build/softdevice_test.bin differ
BUILD OPTIONS:
  SoftDevice  s132
  SDK         11
  nRF         nrf52832
  RAM         64 kB
  FLASH       512 kB
  Board       BOARD_SIMPLE
 
# Write to NVMC to enable erase, do erase all, wait for completion. reset
mkdir -p _build/
printf "w4 4001e504 2\nw4 4001e50c 1\nsleep 100\nr\nexit\n" > _build/erase-all.jlink
mkdir -p _build/
JLinkExe -device nrf52 -if swd -speed 1000  _build/erase-all.jlink
SEGGER J-Link Commander V6.88a (Compiled Nov 18 2020 15:09:53)
DLL version V6.88a, compiled Nov 18 2020 15:09:35


J-Link Command File read successfully.
Processing script file...

J-Link connection not established yet but required for command.
Connecting to J-Link via USB...O.K.
Firmware: J-Link ARM-OB STM32 compiled Aug 22 2012 19:52:04
Hardware version: V7.00
S/N: 20090928
License(s): RDI,FlashDL,FlashBP,JFlash,GDBFull
VTref=3.300V
Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
Found SW-DP with ID 0x2BA01477
Unknown DP version. Assuming DPv0
Scanning AP map to find all available APs
AP[2]: Stopped AP scan as end of AP map has been reached
AP[0]: AHB-AP (IDR: 0x24770011)
AP[1]: JTAG-AP (IDR: 0x02880000)
Iterating through AP map to find AHB-AP to use
AP[0]: Core found
AP[0]: AHB-AP ROM base: 0xE00FF000
CPUID register: 0x410FC241. Implementer code: 0x41 (ARM)
Found Cortex-M4 r0p1, Little endian.
FPUnit: 6 code (BP) slots and 2 literal slots
CoreSight components:
ROMTbl[0] @ E00FF000
ROMTbl[0][0]: E000E000, CID: B105E00D, PID: 000BB00C SCS-M7
ROMTbl[0][1]: E0001000, CID: B105E00D, PID: 003BB002 DWT
ROMTbl[0][2]: E0002000, CID: B105E00D, PID: 002BB003 FPB
ROMTbl[0][3]: E0000000, CID: B105E00D, PID: 003BB001 ITM
ROMTbl[0][4]: E0040000, CID: B105900D, PID: 000BB9A1 TPIU
ROMTbl[0][5]: E0041000, CID: B105900D, PID: 000BB925 ETM
Cortex-M4 identified.
Writing 00000002 -> 4001E504

Writing 00000001 -> 4001E50C

Sleep(100)

Reset delay: 0 ms
Reset type NORMAL: Resets core & peripherals via SYSRESETREQ & VECTRESET bit.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.


Script processing completed.

# Write to NVMC to enable write. Write mainpart, write UICR. Assumes device is erased.
mkdir -p _build/
printf "w4 4001e504 1\nloadbin \"_build/s132_nrf52_2.0.0_softdevice.bin\" 0\nr\ng\nexit\n" > _build/flash-softdevice.jlink
mkdir -p _build/
/Applications/ARM/bin/arm-none-eabi-objcopy -Iihex -Obinary ../../nrf5x-base/make/../sdk/nrf51_sdk_11.0.0//components/softdevice/s132/hex/s132_nrf52_2.0.0_softdevice.hex _build/s132_nrf52_2.0.0_softdevice.bin
JLinkExe -device nrf52 -if swd -speed 1000  _build/flash-softdevice.jlink
SEGGER J-Link Commander V6.88a (Compiled Nov 18 2020 15:09:53)
DLL version V6.88a, compiled Nov 18 2020 15:09:35


J-Link Command File read successfully.
Processing script file...

J-Link connection not established yet but required for command.
Connecting to J-Link via USB...O.K.
Firmware: J-Link ARM-OB STM32 compiled Aug 22 2012 19:52:04
Hardware version: V7.00
S/N: 20090928
License(s): RDI,FlashDL,FlashBP,JFlash,GDBFull
VTref=3.300V
Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
Found SW-DP with ID 0x2BA01477
Unknown DP version. Assuming DPv0
Scanning AP map to find all available APs
AP[2]: Stopped AP scan as end of AP map has been reached
AP[0]: AHB-AP (IDR: 0x24770011)
AP[1]: JTAG-AP (IDR: 0x02880000)
Iterating through AP map to find AHB-AP to use
AP[0]: Core found
AP[0]: AHB-AP ROM base: 0xE00FF000
CPUID register: 0x410FC241. Implementer code: 0x41 (ARM)
Found Cortex-M4 r0p1, Little endian.
FPUnit: 6 code (BP) slots and 2 literal slots
CoreSight components:
ROMTbl[0] @ E00FF000
ROMTbl[0][0]: E000E000, CID: B105E00D, PID: 000BB00C SCS-M7
ROMTbl[0][1]: E0001000, CID: B105E00D, PID: 003BB002 DWT
ROMTbl[0][2]: E0002000, CID: B105E00D, PID: 002BB003 FPB
ROMTbl[0][3]: E0000000, CID: B105E00D, PID: 003BB001 ITM
ROMTbl[0][4]: E0040000, CID: B105900D, PID: 000BB9A1 TPIU
ROMTbl[0][5]: E0041000, CID: B105900D, PID: 000BB925 ETM
Cortex-M4 identified.
Writing 00000001 -> 4001E504

Downloading file [_build/s132_nrf52_2.0.0_softdevice.bin]...
J-Link: Flash download: Bank 0 @ 0x00000000: 1 range affected (114688 bytes)
J-Link: Flash download: Total: 4.888s (Prepare: 0.902s, Compare: 0.076s, Erase: 0.000s, Program & Verify: 3.893s, Restore: 0.015s)
J-Link: Flash download: Program & Verify speed: 28 KB/s
O.K.

Reset delay: 0 ms
Reset type NORMAL: Resets core & peripherals via SYSRESETREQ & VECTRESET bit.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.



Script processing completed.

JLinkExe -device nrf52 -if swd -speed 1000  _build/flash.jlink
SEGGER J-Link Commander V6.88a (Compiled Nov 18 2020 15:09:53)
DLL version V6.88a, compiled Nov 18 2020 15:09:35


J-Link Command File read successfully.
Processing script file...

J-Link connection not established yet but required for command.
Connecting to J-Link via USB...O.K.
Firmware: J-Link ARM-OB STM32 compiled Aug 22 2012 19:52:04
Hardware version: V7.00
S/N: 20090928
License(s): RDI,FlashDL,FlashBP,JFlash,GDBFull
VTref=3.300V
Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.

Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.

Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.

Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.


Script processing completed.

michaelhunt@nicolaskerr openhaystack-alternative %

**Comment by jaekim24** [comment]
when I try flashing the new chip again this shows up and does this mean it worked? Also how do I get this chip to communicate with the openhaystack app, like do I have to add the public advertisement key somewhere: 


michaelhunt@nicolaskerr openhaystack-alternative % TOOLCHAIN_PATH=/Applications/ARM/bin/ make flash
BUILD OPTIONS:
  SoftDevice  s132
  SDK         11
  nRF         nrf52832
  RAM         64 kB
  FLASH       512 kB
  Board       BOARD_SIMPLE
 
mkdir -p _build/
printf "r\n" > _build/flash.jlink
printf "loadfile _build/openhaystack-alternative_s132.hex \nr\ng\nexit\n" >> _build/flash.jlink
mkdir -p _build/
printf "r\nsavebin _build/downloaded_test.bin 0x1000 0x10\nexit\n" > _build/test-softdevice.jlink
mkdir -p _build/
SEGGER J-Link Commander V6.88a (Compiled Nov 18 2020 15:09:53)
DLL version V6.88a, compiled Nov 18 2020 15:09:35


J-Link Command File read successfully.
Processing script file...

J-Link connection not established yet but required for command.
Connecting to J-Link via USB...O.K.
Firmware: J-Link ARM-OB STM32 compiled Aug 22 2012 19:52:04
Hardware version: V7.00
S/N: 20090928
License(s): RDI,FlashDL,FlashBP,JFlash,GDBFull
VTref=3.300V
Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
Found SW-DP with ID 0x2BA01477
Unknown DP version. Assuming DPv0
Scanning AP map to find all available APs
AP[2]: Stopped AP scan as end of AP map has been reached
AP[0]: AHB-AP (IDR: 0x24770011)
AP[1]: JTAG-AP (IDR: 0x02880000)
Iterating through AP map to find AHB-AP to use
AP[0]: Core found
AP[0]: AHB-AP ROM base: 0xE00FF000
CPUID register: 0x410FC241. Implementer code: 0x41 (ARM)
Found Cortex-M4 r0p1, Little endian.
FPUnit: 6 code (BP) slots and 2 literal slots
CoreSight components:
ROMTbl[0] @ E00FF000
ROMTbl[0][0]: E000E000, CID: 00000000, PID: 00000000 ???
ROMTbl[0][1]: E0001000, CID: 00000000, PID: 00000000 ???
Cortex-M4 identified.
Reset delay: 0 ms
Reset type NORMAL: Resets core & peripherals via SYSRESETREQ & VECTRESET bit.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.
Reset: SYSRESETREQ has confused core.
Failed to power up DAP
Reset: Using fallback: VECTRESET.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.VECTRESET.
Reset: VECTRESET has confused core.
Reset: Using fallback: Reset pin.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via reset pin
Reset: VC_CORERESET did not halt CPU. (Debug logic also reset by reset pin?).
Reset: Reconnecting and manually halting CPU.
Failed to power up DAP
CPU could not be halted
Reset: Core did not halt after reset, trying to disable WDT.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via reset pin
Reset: VC_CORERESET did not halt CPU. (Debug logic also reset by reset pin?).
Reset: Reconnecting and manually halting CPU.
Failed to power up DAP
CPU could not be halted
Reset: Failed. Toggling reset pin and trying reset strategy again.
Failed to power up DAP
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.
Reset: SYSRESETREQ has confused core.
Failed to power up DAP
Reset: Using fallback: VECTRESET.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.VECTRESET.
Reset: VECTRESET has confused core.
Reset: Using fallback: Reset pin.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via reset pin
Reset: VC_CORERESET did not halt CPU. (Debug logic also reset by reset pin?).
Reset: Reconnecting and manually halting CPU.
Failed to power up DAP
CPU could not be halted
Reset: Core did not halt after reset, trying to disable WDT.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via reset pin
Reset: VC_CORERESET did not halt CPU. (Debug logic also reset by reset pin?).
Reset: Reconnecting and manually halting CPU.
Failed to power up DAP
CPU could not be halted
CPU could not be halted

****** Error: Failed to halt CPU.

Opening binary file for writing... [_build/downloaded_test.bin]
Reading 16 bytes from addr 0x00001000 into file...Could not read memory.


Script processing completed.

16+0 records in
16+0 records out
16 bytes transferred in 0.000128 secs (124970 bytes/sec)
Files _build/downloaded_test.bin and _build/softdevice_test.bin differ
BUILD OPTIONS:
  SoftDevice  s132
  SDK         11
  nRF         nrf52832
  RAM         64 kB
  FLASH       512 kB
  Board       BOARD_SIMPLE
 
# Write to NVMC to enable erase, do erase all, wait for completion. reset
mkdir -p _build/
printf "w4 4001e504 2\nw4 4001e50c 1\nsleep 100\nr\nexit\n" > _build/erase-all.jlink
mkdir -p _build/
JLinkExe -device nrf52 -if swd -speed 1000  _build/erase-all.jlink
SEGGER J-Link Commander V6.88a (Compiled Nov 18 2020 15:09:53)
DLL version V6.88a, compiled Nov 18 2020 15:09:35


J-Link Command File read successfully.
Processing script file...

J-Link connection not established yet but required for command.
Connecting to J-Link via USB...O.K.
Firmware: J-Link ARM-OB STM32 compiled Aug 22 2012 19:52:04
Hardware version: V7.00
S/N: 20090928
License(s): RDI,FlashDL,FlashBP,JFlash,GDBFull
VTref=3.300V
Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.

Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.

Sleep(100)

Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.


Script processing completed.

# Write to NVMC to enable write. Write mainpart, write UICR. Assumes device is erased.
mkdir -p _build/
printf "w4 4001e504 1\nloadbin \"_build/s132_nrf52_2.0.0_softdevice.bin\" 0\nr\ng\nexit\n" > _build/flash-softdevice.jlink
mkdir -p _build/
/Applications/ARM/bin/arm-none-eabi-objcopy -Iihex -Obinary ../../nrf5x-base/make/../sdk/nrf51_sdk_11.0.0//components/softdevice/s132/hex/s132_nrf52_2.0.0_softdevice.hex _build/s132_nrf52_2.0.0_softdevice.bin
JLinkExe -device nrf52 -if swd -speed 1000  _build/flash-softdevice.jlink
SEGGER J-Link Commander V6.88a (Compiled Nov 18 2020 15:09:53)
DLL version V6.88a, compiled Nov 18 2020 15:09:35


J-Link Command File read successfully.
Processing script file...

J-Link connection not established yet but required for command.
Connecting to J-Link via USB...O.K.
Firmware: J-Link ARM-OB STM32 compiled Aug 22 2012 19:52:04
Hardware version: V7.00
S/N: 20090928
License(s): RDI,FlashDL,FlashBP,JFlash,GDBFull
VTref=3.300V
Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.

Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.

Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.

Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.


Script processing completed.

JLinkExe -device nrf52 -if swd -speed 1000  _build/flash.jlink
SEGGER J-Link Commander V6.88a (Compiled Nov 18 2020 15:09:53)
DLL version V6.88a, compiled Nov 18 2020 15:09:35


J-Link Command File read successfully.
Processing script file...

J-Link connection not established yet but required for command.
Connecting to J-Link via USB...O.K.
Firmware: J-Link ARM-OB STM32 compiled Aug 22 2012 19:52:04
Hardware version: V7.00
S/N: 20090928
License(s): RDI,FlashDL,FlashBP,JFlash,GDBFull
VTref=3.300V
Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.

Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.

Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.

Target connection not established yet but required for command.
Device "NRF52" selected.


Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.


Script processing completed.

michaelhunt@nicolaskerr openhaystack-alternative %

**Comment by acalatrava** [comment]
It seems that you find the same issue as me while loading the firmware. Please try `make e104install` instead. You may need to disconnect and connect VCC while this command is being executed (and maybe several times until it triggers the flash)

**Comment by jaekim24** [comment]
thank you I will try this @acalatrava

**Comment by jaekim24** [comment]
how do I add my advertisement key ?

**Comment by jaekim24** [comment]
<img width="1006" alt="Screen Shot 2021-06-03 at 8 34 28 PM" src="https://user-images.githubusercontent.com/62858192/120728518-196da580-c4ab-11eb-9072-38d9bce4f1ae.png">
im getting this error @acalatrava . Can anyone please help me with this issue, im so close to getting it to work on the nrf52 chip.

**Comment by jaekim24** [comment]
<img width="1006" alt="Screen Shot 2021-06-03 at 8 40 06 PM" src="https://user-images.githubusercontent.com/62858192/120728910-e2e45a80-c4ab-11eb-803f-e3ab87b50959.png">
is it talking about this hex file
