### ISSUE TITLE
micro:bit v2

### ISSUE THREAD

**Issue by yonnath** [acalatrava/openhaystack-firmware#7]
Hola Antonio,

Any chance your firmware works with the micro:bit v2? If so how?

Thanks,
Anthony

**Comment by acalatrava** [comment]
Since microbit v2 are nRF52 based it should work. However I couldn’t test it since I don’t have any. 

Just grab the bin file and flash it accordingly to test it.

**Comment by yonnath** [comment]
Thanks, I'll try

**Comment by aaronjrodrigues** [comment]
did it work?
