### ISSUE TITLE
nRF51822 with/without oscillator build process and energy consumption 

### ISSUE THREAD

**Issue by sebi5361** [acalatrava/openhaystack-firmware#9]
I installed your openhaystack firmware alternative on an [AliExpress beacon](https://www.aliexpress.com/item/32826502025.html) and it works great! Thank you.

I also ordered a [YJ-15013-NRF51822 module](https://www.aliexpress.com/item/32965118537.html) and it is equipped with an oscillator.
Q: Is there a build parameter to specify the use of an oscillator when building the nRF51822 firmware (or should I create a new board definition)?

In the product description it is written: _"Oscillator, in Bluetooth low-power applications, does not require an external 32kHz crystal, can be sectioned"_
Q: Do you think having no oscillator consumes less energy indeed?
Q: Do you think I have to remove physically the oscillator from the board or using the firmware with no oscillator should prevent the microcontroller from powering the oscillator?

**Comment by sebi5361** [comment]
I found my answers regarding power consumption [here](https://devzone.nordicsemi.com/f/nordic-q-a/14214/how-much-current-consumption-when-we-use-internal-32k-rc).
In a nutshell: using an external crystal is more energy efficient than using the internal RC oscillator.
I'll adjust a board definition file according to my needs.
Am closing this issue.

**Comment by lanrat** [comment]
@sebi5361 I have the same beacon. Can you share your board definition file?

Thanks.
